language: node_js
# We use Ruby because we need rvm, but unforunately, on OSX we have to manually install nvm via homebrew.
# See: https://github.com/travis-ci/travis-ci/issues/2311

os:
  - linux
#  - osx

node_js:
  - 5.3.0
  - 5.4.0
  - 4.2.4

cache:
  directories:
    # tsd
    - $TRAVIS_BUILD_DIR/typings/

    # npm
    - $TRAVIS_BUILD_DIR/node_modules/

    # bower:
    - $TRAVIS_BUILD_DIR/bower_components

before_install:
#  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
#  - source /tmp/.nvm/nvm.sh
#  - nvm install $NODE_VERSION
#  - nvm use $NODE_VERSION

#  Versions:
  - npm install -g grunt-cli bower tsd
  - node --version
  - npm --version
  - bower --version

install:
  - npm install
  - bower install
  - gem install sass

  # We do this because of the Github Token issue
  - tsd install

before_script:
  - grunt init build

script:
  - npm test
