# Test against this version of Node.js
environment:
  TSD_GITHUB_TOKEN:
    secure: C+LiIelJ1iZJwJwHbAvLmh865EUB2yk+0kbvJ9iZfoXCwW1WiVn+ZR+y1LtDu34f

  ruby_version: "2.2.2"

  matrix:
    - nodejs_version: "5.3.0"
    - nodejs_version: "5.4.0"
    - nodejs_version: "4.2.4"

cache:
  - node_modules                    # local npm modules
  - typings
  - bower_components
  - '%APPDATA%\npm-cache'             # npm cache

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # Set the ruby path
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ps: >-
      $tsdConfig = @"

      {
          "token": "$($env:TSD_GITHUB_TOKEN)"
      }

      "@

      $tsdConfig | Out-File "$($env:USERPROFILE)\.tsdrc"

  # install global modules
  - npm install -g bower grunt-cli tsd

  # Show some useful info:
  - node --version
  - npm --version
  - bower --version
  - tsd --version
  - tsd rate

  # Install extras
  - gem install sass
  - npm install
  - bower install
  # We do this over `grunt tsd` because of the Github Token issues
  - tsd install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.


  # run tests
  - npm test


# Don't actually build.
build: off
