# Test against this version of Node.js
environment:
  TSD_GITHUB_TOKEN:
    secure: QxRBCgabzBrBfQY3YG2fYeMy2NlxNQ4tSdBTboZ7ZTX0AWPYvVJfU0Q1IH8HaVaQ

  ruby_version: "2.2.2"

  matrix:
    - nodejs_version: "5.3.0"
    - nodejs_version: "5.4.0"
    - nodejs_version: "4.2.4"

cache:
  - node_modules                    # local npm modules
  - typings
  - bower_components
  - '%APPDATA%\npm-cache'           # npm cache

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # Set the ruby path
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%

  # install modules
  - npm install -g bower grunt-cli tsd
  - gem install sass
  - npm install
  - bower install
  # We do this because of the Github Token issue
  - tsd install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - bower --version

  # run tests
  - npm test


# Don't actually build.
build: off
